export enum TextMode {
  PLAIN_TEXT = "text/plain",
  SQL = "text/sql",
  JAVASCRIPT = "text/javascript",
  PYTHON = "python",
  SHELL = "shell",
  JSON = "application/json",
}

export enum ConfigurationType {
  STRING = "STRING",
  TAGS = "TAGS",
  DEBOUNCE_STRING = "DEBOUNCE_STRING",
  NUMBER = "NUMBER",
  BOOLEAN = "BOOLEAN",
  BOOLEAN_SWITCH = "BOOLEAN_SWITCH",
  TEXT_AREA = "TEXT_AREA",
  TEXT_CODE = "TEXT_CODE",
  SQL = "SQL",
  MAP = "MAP",
  LIST = "LIST",
  LIST_BEAN = "LIST_BEAN",
  MODEL = "MODEL",
  RADIO_GROUP = "RADIO_GROUP",
  CHECKBOX_GROUP = "CHECKBOX_GROUP",
  VALUE_CHOOSER = "VALUE_CHOOSER",
  MULTIPLE_VALUE_CHOOSER = "MULTI_VALUE_CHOOSER",
  INPUT_STREAM = "INPUT_STREAM",
  FORMULA_EDITOR = "FORMULA_EDITOR",
  APPEND_ROW_SCHEMA = "APPEND_ROW_SCHEMA",
  PREVIEW_INPUTS = "PREVIEW_INPUTS",
  LIST_SELECTOR = "LIST_SELECTOR",
  // 分组或美观
  LABEL = "LABEL",
  DIVIDER = "DIVIDER",
  HEADER = "HEADER",
  ROW_GROUP = "ROW_GROUP",
  FIELD_SELECTOR = "FIELD_SELECTOR",
  MULTI_FIELD_SELECTOR = "MULTI_FIELD_SELECTOR", // 选择列+重命名
  GROUP_VALUE_CHOOSER = "GROUP_VALUE_CHOOSER",
  // 逻辑分组
  LOGIC_SWITCH = "LOGIC_SWITCH",
  // 隐藏
  HIDDEN = "HIDDEN",
  // 字段同步Hack = fieldSync
  FIELD_SYNC = "FIELD_SYNC",
  // 选择列
  CHECKBOX_FIELD_SELECTOR = "CHECKBOX_FIELD_SELECTOR",
  // 定制化异步请求
  ASYNC_TABLES = "ASYNC_TABLES",
  ASYNC_TABLE_COLUMNS = "ASYNC_TABLE_COLUMNS",
  KNOWLEDGE_BASE = "KNOWLEDGE_BASE",
}

export enum PanelType {
  CONVENTIONAL = "CONVENTIONAL",
  NODE_CONFIG = "NODE_CONFIG",
  RUN_OPTION = "RUN_OPTION",
}
